#include <stdio.h>
#include <stdlib.h>
#include "pico/stdlib.h"
#include "hardware/gpio.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"
#include "hardware/watchdog.h"
#include <string.h>

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to
#define MAX_WORD_SIZE 50
#define delay_ms 0x7fffff 	   // Number of milliseconds before watchdog will reboot without watchdog_update 
                            //being called. Maximum of 0x7fffff, which is approximately 8.3 seconds

// Declare the main assembly code entry point.
void main_asm();
/* **************************** GLOBAL VARIABLES ************************************ */

int remaining_lives = 3;
int game_start = 0;
char input_morse[MAX_WORD_SIZE];
int input_index = 0;
int input_finished = 0;
int level_selected = 0;
int current_level = 0;
int current_index = 0;
int correct_answers = 0;
int incorrect_answers = 0;
int correct_in_a_row = 0;
int current_word = 0;
const uint RESTART_PERIOD_MS = 3500;

/* **************************** WATCHDOG ************************************ */
void init_watchdog() {
    if (watchdog_caused_reboot()) {
        printf("Rebooted by Watchdog!\n");
     } 
     if(watchdog_enable_caused_reboot()) {
        printf("Chip reboot by Watchdog Enable\n");
     }
    
     // Enable the watchdog, requiring the watchdog to be updated every 8.3s or the chip will reboot
     // second arg is pause on debug which means the watchdog will pause when stepping through code
     watchdog_enable(delay_ms, 1);
     watchdog_update();
     
}

void asm_watchdog() {
     watchdog_update();
}


/* **************************** GPIO ************************************ */

// Initialise a GPIO pin – see SDK for detail on gpio_init()
void asm_gpio_init(uint pin) {
    gpio_init(pin);
}

// Set direction of a GPIO pin – see SDK for detail on gpio_set_dir()
void asm_gpio_set_dir(uint pin, bool out) {
    gpio_set_dir(pin, out);
}

// Get the value of a GPIO pin – see SDK for detail on gpio_get()
bool asm_gpio_get(uint pin) {
    return gpio_get(pin);
}

// Set the value of a GPIO pin – see SDK for detail on gpio_put()
void asm_gpio_put(uint pin, bool value) {
    gpio_put(pin, value);
}

// Enable falling-edge interrupt – see SDK for detail on gpio_set_irq_enabled()
void asm_gpio_set_irq(uint pin) {
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_FALL, true);
    gpio_set_irq_enabled(pin, GPIO_IRQ_EDGE_RISE, true);
}

void sleep_asm() {
   sleep_ms(RESTART_PERIOD_MS);
}

/* **************************** TIME ************************************ */
/**
 * records absolute_time_t for gpio interrupt
*/
int get_time() {
    absolute_time_t t = get_absolute_time();
    return to_ms_since_boot(t);
    //return time_us_64();
}
/**
 * gets difference betweeen times for gpio interrupt
*/
int get_time_difference(int end, int start) {
    return end-start;
}


/* **************************** RGB ************************************ */
/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}


/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit paramaters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composit 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}


/**
 * @brief EXAMPLE - WS2812_RGB
 *        Simple example to initialise the NeoPixel RGB LED on
 *        the MAKER-PI-PICO and then flash it in alternating
 *        colours between red, green and blue or purple based off remaining
 *        lives.
 * 
 * @return int  Application return code (zero for success).
 */
void RGB_Display() {

    if(game_start == 0) {
        put_pixel(urgb_u32(0x00, 0x00, 0x7F)); // Set the RGB LED to BLUE
    } else {
        if (remaining_lives == 0) {
            put_pixel(urgb_u32(0x7F, 0x00, 0x00)); // Set the RGB LED to RED
            printf("\n**************************** GAME OVER ************************************\n");
        }
        else if (remaining_lives == 1)
        {
            put_pixel(urgb_u32(0xFF, 0xA5, 0x00)); // Set the RGB LED color to ORANGE
            printf("\n**************************** 1 LIFE REMAINING ************************************\n");
        }
        else if (remaining_lives == 2)
        {
            put_pixel(urgb_u32(0x4B, 0x00, 0x82)); // Set the RGB LED color to PURPLE
            printf("\n**************************** 2 LIVES REMAINING ************************************\n");
        }
        else if (remaining_lives == 3)
        {
            put_pixel(urgb_u32(0x00, 0x7F, 0x00)); // Set the RGB LED color to GREEN
            printf("\n**************************** 3 LIVES REMAINING ************************************\n");
        }
        else
        {
            put_pixel(urgb_u32(0x00, 0x00, 0x00)); // Set the RGB LED color to OFF
            printf("ERROR INVALID NUMBER OF LIVES\n");
        }
    } 

}

/* **************************** MORSE CODE  ************************************ */

const char MORSE_CODE[][6] = {
    "-----",    // 0 
    ".----",    // 1
    "..---",    // 2
    "...--",    // 3
    "....-",    // 4
    ".....",    // 5
    "-....",    // 6
    "--...",    // 7
    "---..",    // 8
    "----.",    // 9 
    ".-",       // A 
    "-...",     // B
    "-.-.",     // C
    "-..",      // D
    ".",        // E
    "..-.",     // F
    "--.",      // G
    "....",     // H
    "..",       // L
    ".---",     // J
    "-.-",      // K
    ".-..",     // L
    "--",       // M
    "-.",       // N
    "---",      // O
    ".--.",     // P
    "--.-",     // Q
    ".-.",      // R
    "...",      // S
    "-",        // T
    "..-",      // U
    "...-",     // V
    ".--",      // W
    "-..-",     // X
    "-.--",     // Y
    "--..",     // Z 
    "X"         // error
};
const char ALPHANUMERIC[][2] = {
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "?"
};

const char WORDS_MORSE[][21] = {
    "-..---",
    "-.-.----...",
    "-.-.-.--...",
    "-..--.",
    ".......---.--.",
    ".....-..",
    "-.-..-.......",
    "--.-..-.",
    "-.-.---.-..",
    "......-...--.",
    "-.....-...",
    ".--...-.-.---"
};

const char WORDS_ALPHANUMERIC[][5] = {
    "TEAM",
    "CODE",
    "KEYS",
    "TIME",
    "SHOP",
    "SEED",
    "CASH",
    "MAIN",
    "CORE",
    "HELP",
    "BITS",
    "PICO"
};

/* **************************** PRINT MESSAGES  ************************************ */

void welcome_message() {
    printf(           "\n _.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._.-=-._\n");
    printf(           ".-'---      - ---     --     ---   -----   - --       ----  ----   -     ---`-.\n");
    printf(           " )                                                                           (\n");
    printf(            "(                                                                             )\n" );
    printf(            " )                                WELCOME                                    (\n" );
    printf(            "(                          GROUP 43 MORSE CODE GAME                           )\n" );
    printf(            " )                            You have 3 lives                                 (\n" );
    printf(            "(                                                                            )\n" );
    printf(            " )                              LEVEL 1 & 2                                  (\n" );
    printf(            "(          You will be presented with an alphanumeric character (A-Z/0-9)     )\n" );
    printf(            " )                              LEVEL 3 & 4                                 (\n" );
    printf(            "(          You will be presented with an alphanumeric word                    )\n" );
    printf(            " )                                                                           (\n" );
    printf(            "(     Enter the correct equivalent Morse Code sequence 5 times to progress!  )\n" );
    printf(            " )                                                                           (\n" );
    printf(            "(___       _       _       _       _       _       _       _       _       ___)\n" );
    printf(            "    `-._.-' (___ _) `-._.-' `-._.-' )     ( `-._.-' `-._.-' (__ _ ) `-._.-'\n" );
    printf(            "            ( _ __)                (_     _)                (_ ___)\n" );
    printf(            "            (__  _)                 `-._.-'                 (___ _)\n" );
    printf(            "            `-._.-'                                         `-._.-'\n");  
}
void win_message() {
    printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                        YOU WIN !                      )\n" );                   
     printf(            "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void lose_message() {
    printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                        YOU LOSE :(                    )\n" );                   
     printf(            "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void select_level_display() {
     printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )  Choose level corresponding to ascending difficulty  )\n" );
    printf(             "\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )           LEVEL 1 -> INPUT 1(.----)                   )\n" );
    printf(             "    (            LEVEL 2 -> INPUT 2(..---)                 (\n" );
    printf(             "     )           LEVEL 3 -> INPUT 3(...--)                  )\n" );
    printf(             "    (            LEVEL 4 -> INPUT 4(....-)                 (\n" );
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                                                      )\n" );
    printf(             "\n" );
    printf(             "    (                                                      (\n" );
     printf(            "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void print_question_1(int tmp) {
     printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )  ENTER THE FOLLOWING CHARACTER(MORSE PROVIDED)       )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                    %s -> MORSE(%s)                   )\n", ALPHANUMERIC[tmp], MORSE_CODE[tmp]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}
void print_question_2(int tmp) {
     printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )             ENTER THE FOLLOWING CHARACTER            )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                        %s                            )\n", ALPHANUMERIC[tmp]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}
void print_question_3(int tmp) {
    printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )  ENTER THE FOLLOWING CHARACTER(MORSE PROVIDED)       )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                    %s -> MORSE(%s)                   )\n", WORDS_ALPHANUMERIC[tmp], WORDS_MORSE[tmp]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void print_question_4(int tmp) {
    printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )          ENTER THE FOLLOWING CHARACTER               )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                      %s                              )\n", WORDS_ALPHANUMERIC[tmp]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

/**
 *  returns the integer percent to be printed.
*/
int percent(int a, int b) {
    return (100*a + b/2)/b;
}

void print_incorrect_summary() {
      printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )            CURRENT LEVEL FAILED                      )\n" );
    printf(             "    (               RAN OUT OF LIVES                       (\n" );
    printf(             "     )                    STATS                             )\n" );
    printf(             "     )              Correct Answers: %d                      )\n", correct_answers);
    printf(             "    (               Incorrect Answers: %d                   (\n" , incorrect_answers);
    printf(             "     )              Percentage Correct: %d%%               )\n" , percent(correct_answers, (int)(correct_answers + incorrect_answers)));
     printf(            "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void print_correct_summary() {
      printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )            CURRENT LEVEL COMPLETE                     )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                    STATS                             )\n" );
    printf(             "    (               REMAINING LIVES: %d                    (\n", remaining_lives );    
    printf(             "     )              Correct Answers: %d                      )\n", correct_answers);
    printf(             "    (               Incorrect Answers: %d                   (\n" , incorrect_answers);
    printf(             "     )              Percentage Correct: %.2f%%              )\n" ,  percent(correct_answers, (int)(correct_answers + incorrect_answers)));
    printf(             "    (                                                      (\n" );
     printf(            "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}



void print_correct_char() {
     printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                  CORRECT YOU ENTERED:                )\n" );
    printf(             "    (                          %s                            (\n" , input_morse);
    printf(             "     )                    %s -> MORSE(%s)                   )\n", ALPHANUMERIC[current_index], MORSE_CODE[current_index]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void print_incorrect_char(int tmp) {
     printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                 INCORRECT YOU ENTERED:                )\n" );
    printf(             "    (                     %s ->MORSE(%s)                    (\n" , ALPHANUMERIC[tmp], input_morse);
    printf(             "     )    CORRECT ANSWER: %s -> MORSE(%s)                   )\n", ALPHANUMERIC[current_index], MORSE_CODE[current_index]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void print_incorrect_word() {
     printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                      (\n" );
    printf(             "     )                 INCORRECT YOU ENTERED:                )\n" );
    printf(             "    (                          %s                            (\n" , input_morse);
    printf(             "     )                    %s -> MORSE(%s)                   )\n", WORDS_ALPHANUMERIC[current_word-1], WORDS_MORSE[current_word-1]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}

void print_correct_word() {
     printf(             "     _______________________________________________________\n" );
    printf(             "    /\\                                                      \\\n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/''''''''''''''''''''''''''''''''''''''''''''''''''''''/\n" );
    printf(             "    (                                                       (\n" );
    printf(             "     )                 CORRECT YOU ENTERED:                  )\n" );
    printf(             "    (                          %s                            (\n" , input_morse);
    printf(             "     )                    %s -> MORSE(%s)                   )\n", WORDS_ALPHANUMERIC[current_word-1], WORDS_MORSE[current_word-1]);
    printf(             "     )                                                      )\n" );
    printf(             "    (                                                      (\n" );
    printf(             "    /\\''''''''''''''''''''''''''''''''''''''''''''''''''''''\\    \n" );
    printf(             "(O)===)><><><><><><><><><><><><><><><><><><><><><><><><><><><)==(O)\n" );
    printf(             "    \\/______________________________________________________/\n");  
}







/* **************************** SELECT LEVEL ************************************ */

void boolean_level() {
    level_selected = 1;
}

/**
 * compares user input to 4 potential levels
 * return that level if they are equal
*/

int select_level() {
    if (strcmp(input_morse, MORSE_CODE[1])==0)
    {
        printf("\n**************************** SELECTED LEVEL 1 ************************************\n");
        return 1; // return 1 if equal
    }
    else if(strcmp(input_morse, MORSE_CODE[2])==0) {
        printf("\n**************************** SELECTED LEVEL 2 ************************************\n");
        return 2; // return 2 if equal
    }
    else if(strcmp(input_morse, MORSE_CODE[3])==0) {
        printf("\n**************************** SELECTED LEVEL 3 ************************************\n");
        current_word++;
        return 3; // return 3 if equal
    }
    else if(strcmp(input_morse, MORSE_CODE[4])==0) {
        printf("\n**************************** SELECTED LEVEL 4 ************************************\n");
        current_word++;
        return 4; // return 4  if equal
    }
    else {
        printf("\n**************************** INVALID INPUT ************************************\n");
        return 0;
    }
}
int get_level() {
    return current_level;
}

void set_level(int level) {
    current_level = level;
}

void set_word(int word) {
    current_word = word;
}

void restart_game() {
    remaining_lives = 3;
    level_selected = 0;
    RGB_Display();
}

/**
 * checks if there have been 5 correct answers in a row,
 *  if this is true either increases the level, 
 *  updating the answer global variable, or if the player is on level 4, 
 * completes the game and prints a win message. If there has not been 5
 * correct answers in a row, checks if remaining_lives = 0, if this is
 *  true, ends the game.
*/

int check_level_complete() {
    if(correct_in_a_row == 5) {
        print_correct_summary();
        if(current_level == 4) {
            win_message();
            return 2;
        } 
        incorrect_answers =0;
        correct_answers = 0;
        correct_in_a_row = 0;
        current_level++;
        if(current_level == 3) {
            current_word = 1;
        }
        return 1;
    }
    if(remaining_lives == 0) {
        lose_message();
        print_incorrect_summary();
        return 2;
    } 
    return 0;
}

/* **************************** LEVEL QUESTIONS ************************************ */


int get_random(int min, int max){
   return min + rand() / (RAND_MAX / (max - min + 1) + 1);
}
/**
 * randomizes the words the player gets based on current_word,
 *  the index from the previous question.
*/
void change_word() {
    if(current_word < 11) {
        if(current_word < 6) {
            current_word = get_random(6, 11);
        } else  if(current_word > 8) {
            current_word = get_random(0, 7);
        } else {
            current_word++;
        }
    } else {
        current_word=1;
    }
}

int level_1_question() {
    int tmp = get_random(0, 35);
    print_question_1(tmp);
    current_index = tmp;
    return tmp;
}

int level_2_question() {
    int tmp = get_random(0, 35);
    print_question_2(tmp);
    current_index = tmp;
    return tmp;
}

int level_3_question() {
    change_word();
    if(current_word > 0 && current_word <=11) {
        print_question_3(current_word-1);
    }
    return current_word;
}

int level_4_question() {
    change_word();
    if(current_word > 0 && current_word <=11) {
        print_question_4(current_word-1);
    }
    return current_word;
}
/**
 *  prints questions based on current_level.
*/
void print_question() {
    if(current_level == 1) {
        level_1_question();
    } else if(current_level == 2) {
        level_2_question();
    } else if(current_level == 3) {
        level_3_question();
    } else if(current_level == 4) {
        level_4_question();
    } 
}
/* **************************** DECTECTING INPUT ************************************ */


/**
 * clears input and sets index to 0, as marking the input as not complete
*/
void init_input() {
    for(int i=0;i<MAX_WORD_SIZE;i++) {
        input_morse[i] =  '\0';
    }
    input_finished = 0;
    input_index = 0;
    printf("\nYOUR INPUT: ");
}

/**
 * Called from user input loops in assembly and either writes dot(.) 
 * or dash(-) to user input or finished user input.  
*/

int write_input(int input) {

    if (input == 1) {                           // 1 = "."
        input_morse[input_index] = '.'; // add '.' to the array
        input_index++;
        printf(".");
    } else if (input == 2) {                           // 2 = "-"
        input_morse[input_index] = '-'; // add '-' to the array
        input_index++;
        printf("-");
    }
    else if (input == 4 && level_selected == 1) {  // 4 = "enter"
        
        input_finished = 1;  // value = 1 if answer is correct, otherwise remain 0
    } else if (input == 4 && level_selected == 0) { // 4 = "enter"
     

        input_finished = 1;  // value = 1 if answer is correct, otherwise remain 0
        return select_level();
    } else {
        printf("ERROR INVALID INPUT");
    }
    return -1;
}


/* **************************** CHECKING INPUT ************************************ */
int check_char_input()
{
    if (strcmp(input_morse, MORSE_CODE[current_index])==0)
    {
        return 1; // return 1 if equal
    }
    else
        return 0; // return 0 if not
}

int check_word_input() {
        if (strcmp(input_morse, WORDS_MORSE[current_word-1])==0)
        {
            return 1; // return 1 if equal
        }
        else {
            return 0; // return 0 if not
        }
}

/*
* iterates through the morse code table to see if the user input
* matches any. If it does we output this in print_incorrect_char(), 
* if it doesn’t we output “?”. 

*/
int check_if_valid(){
    for(int i =0; i < 36; i++) {
        if(strcmp(input_morse, MORSE_CODE[i])==0) {
            return i;
        }
    }
    return -1;
}

/**
 * If level 1 or 2 checks user input against the morse table. 
 * If level 3 or 4 checks user input against the morse code word array.
 *  Prints output and updates global variables for answers and remaining lives.
*/

void check_input() {
    if(current_level == 1 || current_level == 2) {
        if(input_finished == 1) {
            if(check_char_input() == 1) {
                print_correct_char();
                correct_answers++;
                correct_in_a_row++;
                if (remaining_lives <3 && remaining_lives > 0) {
                    remaining_lives++;
                }
            } else {
                int tmp = check_if_valid(); 
                if(tmp != -1) {
                    print_incorrect_char(tmp);
                } else {
                    print_incorrect_char(36);
                }
                incorrect_answers++;
                correct_in_a_row = 0;
                remaining_lives--;
            }

        }
    } 
    else if(current_level == 3 || current_level == 4) {
        if(input_finished == 1) {
            if(check_word_input() == 1) {
                print_correct_word();
                correct_answers++;
                correct_in_a_row++;
                if (remaining_lives <3 && remaining_lives > 0) {
                    remaining_lives++;
                }
            } else {
                print_incorrect_word();
                remaining_lives--;
                correct_in_a_row = 0;
                incorrect_answers++;
            }

        }
    } else {
        printf("***ERROR***");
    }
    RGB_Display();
}

int check_input_empty() {
    if(input_index == 0) {
        return 1;
    } else {
        return 0;
    }
}

/* **************************** MAIN FUNCTION ************************************ */

// Main entry point of the application
int main() {
    stdio_init_all();              // Initialise all basic IO
    init_watchdog();
     // Initialise the PIO interface with the WS2812 code (FOR RBG LED)
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);
    RGB_Display();
    game_start = 1;
    watchdog_update();
    welcome_message();
    main_asm();                    // Jump into the ASM code
    return 0;                      // Application return code
}
